### ISSUE TITLE
Vision and mission  discussion

### ISSUE THREAD

**Issue by cess18Milla** [codedevsolutions/Project-Planning#2]
Write  down ur ideas what vision or mission do your propose the whole name entails for us and the clients check timetree for calendar updates

**Comment by jorenlee** [comment]
to be checked by @cess18Milla 

Mission
     To Exhibit creative valuable long term dev integrity solutions.

Vision
    To maintain excellent feedbacks instinctively with fun working environment that solve problems.

**Comment by cess18Milla** [comment]
Mission
Exhibiting work ethics that provides business solutions.

Vision
Delivering stability in economic changes to businesses for long term solutions.
